const $=id=>document.getElementById(id);
const fields=['invoiceNo','invoiceDate','dueDate','clientName','clientUpi','project','service','paymentMethod','projectTotal','currentPayment','previousReceived','utr','transactionId','paymentDateTime','receivedIn','payerUpi','debitedFrom','recipient','recipientUpi','notes'];
const demo={invoiceNo:'SAM-INV-2026-019',invoiceDate:'2026-09-19',dueDate:'2026-09-19',clientName:'Anuradha S Raju',clientUpi:'ashaara203@ibl',project:'CALISTA VITA',service:'Custom Service Marketplace Website Development',paymentMethod:'UPI / PhonePe',projectTotal:0,currentPayment:1000,previousReceived:0,utr:'643620717122',transactionId:'T2609120929453063213453',paymentDateTime:'2026-09-19T13:44',receivedIn:'Canara Bank •••• 6599',payerUpi:'ashaara203@ibl',debitedFrom:'Account ending 25',recipient:'SANTHOSH S',recipientUpi:'santhosh.410@superyes',notes:'This is a payment received toward the CALISTA VITA project.\nPayment was received through UPI; sender and recipient details are recorded above.\nThis invoice is computer generated and does not require a signature.'};
function today(){return new Date().toISOString().slice(0,10)}
function nextInvoice(){let n=Number(localStorage.getItem('samInvoiceSeq')||20);return `SAM-INV-${new Date().getFullYear()}-${String(n).padStart(3,'0')}`}
function money(v){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(v)||0)}
function words(n){n=Math.round(Number(n)||0);if(!n)return '₹0 (Zero Only)';const ones=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'];const tens=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];function two(x){return x<20?ones[x]:tens[Math.floor(x/10)]+(x%10?' '+ones[x%10]:'')}function part(x){let s='';if(x>=100)s+=ones[Math.floor(x/100)]+' Hundred ';x%=100;if(x)s+=two(x);return s.trim()}const original=n;let s='';if(n>=10000000){s+=part(Math.floor(n/10000000))+' Crore ';n%=10000000}if(n>=100000){s+=part(Math.floor(n/100000))+' Lakh ';n%=100000}if(n>=1000){s+=part(Math.floor(n/1000))+' Thousand ';n%=1000}if(n)s+=part(n);return `₹${new Intl.NumberFormat('en-IN').format(original)} (Rupees ${s.trim()} Only)`}
function fmtDate(v){if(!v)return '';const d=new Date(v+'T00:00:00');return isNaN(d)?v:d.toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}
function fmtDateTime(v){if(!v)return '';const d=new Date(v);if(isNaN(d))return v;return d.toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})+' • '+d.toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}
function status(total,received){if(!total)return 'Received';if(received<=0)return 'Pending';if(received>=total)return 'Cleared';return 'Partially Paid'}
function getData(){const d={};fields.forEach(f=>d[f]=$(f).value);return d}
function setData(d){fields.forEach(f=>{if(d[f]!==undefined)$(f).value=d[f]});render()}
function render(){const d=getData();const total=Number(d.projectTotal)||0,current=Number(d.currentPayment)||0,previous=Number(d.previousReceived)||0,received=current+previous,pending=Math.max(total-received,0),st=status(total,received);document.querySelectorAll('[data-out]').forEach(el=>{const k=el.dataset.out;let v=d[k]||'';if(k==='invoiceDate'||k==='dueDate')v=fmtDate(v);if(k==='paymentDateTime')v=fmtDateTime(v);if(['currentPayment','totalReceived','pending','projectTotal'].includes(k))v=money(k==='currentPayment'?current:k==='totalReceived'?received:k==='pending'?pending:total);if(k==='currentPaymentWords')v=words(current);if(k==='status')v=st;if(k==='statusLower')v=st.toLowerCase();el.textContent=v});$('notesOut').textContent=d.notes||'';$('currentDisplay').textContent=money(current);$('receivedDisplay').textContent=money(received);$('pendingDisplay').textContent=money(pending);$('statusDisplay').textContent=st;$('verificationBadge').textContent=total&&received>total?'Check: received exceeds project total':'Ready for verification';$('verificationBadge').className='verification '+(total&&received<=total?'ok':'');localStorage.setItem('samBillDraft',JSON.stringify(d));$('saveStatus').textContent='Draft auto-saved'}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function clearNew(){const d={...demo};d.invoiceNo=nextInvoice();d.invoiceDate=today();d.dueDate=today();d.currentPayment=0;d.previousReceived=0;d.projectTotal=0;d.utr='';d.transactionId='';d.paymentDateTime='';d.receivedIn='';d.payerUpi='';d.debitedFrom='';d.notes='This is a payment received toward the project.\nPayment was received through UPI; sender and recipient details are recorded above.\nThis invoice is computer generated and does not require a signature.';setData(d);localStorage.removeItem('samBillSaved');toast('New bill ready')}
function saveData(){localStorage.setItem('samBillSaved',JSON.stringify(getData()));toast('Bill data saved in this browser')}
async function pdf(){render();const el=$('invoicePreview');const opt={margin:0,filename:($('invoiceNo').value||'SAM-Invoice')+'.pdf',image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#ffffff'},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}};await html2pdf().set(opt).from(el).save();toast('PDF saved')}
function parseOCR(text){const t=text.replace(/\s+/g,' ').trim();const pick=re=>{const m=t.match(re);return m?m[1].trim():''};const amount=pick(/(?:amount received|total amount received|payment received)[^₹0-9]{0,30}(?:₹|rs\.?|inr)?\s*([\d,]+)/i);const utr=pick(/(?:upi reference|utr)\s*[:#-]?\s*([A-Z0-9]+)/i);const txn=pick(/(?:phonepe transaction id|transaction id)\s*[:#-]?\s*([A-Z0-9]+)/i);const upi=pick(/(?:payer upi id|upi id)\s*[:#-]?\s*([\w.-]+@[\w.-]+)/i);if(amount)$('currentPayment').value=amount.replace(/,/g,'');if(utr)$('utr').value=utr;if(txn)$('transactionId').value=txn;if(upi)$('payerUpi').value=upi;const client=pick(/(?:payment received from|payer name|client name)\s*[:#-]?\s*([A-Za-z][A-Za-z .]+)/i);if(client)$('clientName').value=client;render()}
let selectedFile=null;
$('screenshotInput').addEventListener('change',e=>{selectedFile=e.target.files[0];$('ocrBtn').disabled=!selectedFile;$('ocrStatus').textContent=selectedFile?selectedFile.name:'No screenshot selected'});
$('ocrBtn').addEventListener('click',async()=>{if(!selectedFile)return;$('ocrBtn').disabled=true;$('ocrStatus').textContent='Reading screenshot…';try{const r=await Tesseract.recognize(selectedFile,'eng',{logger:m=>{if(m.status==='recognizing text')$('ocrStatus').textContent=`OCR ${Math.round(m.progress*100)}%`}});parseOCR(r.data.text);$('ocrStatus').textContent='Extracted — review and correct fields';toast('Screenshot values extracted')}catch(e){console.error(e);$('ocrStatus').textContent='OCR failed — enter values manually';toast('OCR failed')}finally{$('ocrBtn').disabled=false}});
fields.forEach(f=>$(f).addEventListener('input',render));
$('generateBtn').addEventListener('click',()=>{render();toast('Bill generated and verified in preview')});
$('saveBtn').addEventListener('click',saveData);
$('clearBtn').addEventListener('click',clearNew);
$('loadDemoBtn').addEventListener('click',()=>{setData(demo);toast('Example bill loaded')});
$('downloadBtn').addEventListener('click',pdf);
$('printBtn').addEventListener('click',()=>{render();window.print()});
(function init(){const saved=localStorage.getItem('samBillSaved');const draft=localStorage.getItem('samBillDraft');setData(saved?JSON.parse(saved):draft?JSON.parse(draft):{...demo,invoiceNo:nextInvoice(),invoiceDate:today(),dueDate:today(),currentPayment:0,previousReceived:0,projectTotal:0,utr:'',transactionId:'',paymentDateTime:'',receivedIn:'',payerUpi:'',debitedFrom:''})})();